### PR TITLE
Rename asset_id -> (ga_asset_id, assetHash) to avoid confusion

### PR DESCRIPTION
**Pull request by jkozera**

### CODE REVIEW

**Comment by jtimon** [comment]
concept ACK.
Maybe you can get the database to use the real asset_id as id, but it's probably not worth it.

**Comment by chrisinajar** [comment]
utACK

should it be `gaAssetId` so that both are camel instead of using different naming styles?

**Comment by jkozera** [comment]
> Maybe you can get the database to use the real asset_id as id, but it's probably not worth it.

Hmm, I'd say it's simpler and more generic if we use custom numeric ids. This way backend can work also if assets are implemented in different ways, like maybe with multiple chains.

> should it be `gaAssetId` so that both are camel instead of using different naming styles?

I'm not sure if it's worth changing at this point. The server-side convention is to use underscores, and current convention around all transaction data is underscores in the client too. So the only place that would be feasible to use camel case AFAICS is [the value returned from `_getTransactions`](https://github.com/jkozera/GreenAddressWebFiles/blob/c107a2e31a4feb39937102c3ec04611aeed431cd/static/js/greenwallet/services/wallets.js#L614), and every other key there is underscored, and  other places would require server-side changes too.

**Comment by jkozera** [comment]
Merged as 08f9d3afba2ebaf608c2f5a2deda2999df564b5f.

**Pull request closed without merging**
